#!/usr/bin/env python3
"""Phase 6 of djachenko/PLAN.md: entries.tsv -> djachenko/djachenko.typ (+ PDF), set like the 1900 original.

    python3 tools/dj_build.py                        # the whole dictionary (main part + supplement)
    python3 tools/dj_build.py --subset links         # only the entries linked to the akathist lemmas (links.tsv)
    python3 tools/dj_build.py --leaves 38-60         # a range of leaves of scan A, for a quick look
    python3 tools/dj_build.py --marks                # underline the places where the witnesses disagree
    python3 tools/dj_build.py --no-refs --no-pdf     # without the grey page references; .typ only

The page follows the original (measured on scan A, 600 ppi): A4 with the original's text block of 169 x 249 mm,
two columns of 82.5 mm with a 5.3 mm gutter and a rule between them, 12.6 pt line pitch, a hanging indent of
4.9 mm; the page number centred at the top over a short double rule, the guide words (first three letters of the
first and last headword, with a dash) in Church Slavonic type at the outer ends; the running title "Церк.-славян.
словарь свящ. Г. Дьяченко." with the signature number at the foot of every sixteenth page, as in the book. A letter
section begins with a large initial (in the column — the original centres it across both). Headwords are set in
Ponomar Unicode (the Synodal Church Slavonic typeface), everything else in Old Standard TT (a revival of the civil
type of the period, with the pre-reform letters and polytonic Greek); both fonts are OFL and fetched into
djachenko/fonts/ when missing.

Marks of the digital edition (not in the original): a headword that has not yet been read from the image (Phase 3b
step 2 pending; hw_provisional in entries.tsv) is printed grey; the italics are those ABBYY detected (incomplete);
at the end of every entry a small grey ¶ with the page and column of the 1900 edition (--no-refs to drop it); with
--marks the spans where witnesses D and B disagree are underlined. The front matter states all of this.
"""
import argparse, csv, datetime, re, shutil, subprocess, sys, urllib.request
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from dj_witness import DJ  # noqa: E402

ROOT = DJ.parent
ENTRIES, LINKS = DJ / 'entries.tsv', DJ / 'links.tsv'
TYP, PDF = DJ / 'djachenko.typ', DJ / 'djachenko.pdf'
FONTS = DJ / 'fonts'
FONT_FILES = {
    'PonomarUnicode.otf': 'https://raw.githubusercontent.com/typiconman/fonts-cu/master/Ponomar/PonomarUnicode.otf',
    'OFL-fonts-cu.txt': 'https://raw.githubusercontent.com/typiconman/fonts-cu/master/OFL.txt',
    'OldStandard-Regular.ttf': 'https://raw.githubusercontent.com/google/fonts/main/ofl/oldstandardtt/OldStandard-Regular.ttf',
    'OldStandard-Italic.ttf': 'https://raw.githubusercontent.com/google/fonts/main/ofl/oldstandardtt/OldStandard-Italic.ttf',
    'OldStandard-Bold.ttf': 'https://raw.githubusercontent.com/google/fonts/main/ofl/oldstandardtt/OldStandard-Bold.ttf',
    'OFL-oldstandard.txt': 'https://raw.githubusercontent.com/google/fonts/main/ofl/oldstandardtt/OFL.txt',
}
FRONT_PAGES = 2                         # title page + note; the dictionary's own page numbers start after them

PREAMBLE = r'''// Generated by tools/dj_build.py from djachenko/entries.tsv — do not edit; re-run the script.
// Compile with:  typst compile --font-path djachenko/fonts djachenko/djachenko.typ
#set document(title: "Полный церковно-славянскій словарь (Г. Дьяченко, 1900) — digital edition")
#let cs(body) = text(font: "Ponomar Unicode", body)
#let guide(s) = cs(text(size: 10.5pt, s))
#set text(font: ("Old Standard TT", "PT Serif", "Libertinus Serif"), size: %(size)spt, lang: "ru", hyphenate: false)
#show regex("\p{Greek}[\p{Greek}\p{M}]*"): set text(font: ("Old Standard TT", "Libertinus Serif"))
#set par(justify: true, leading: %(leading)sem, spacing: %(leading)sem, hanging-indent: 4.9mm)
#set columns(gutter: 5.3mm)
#set page(
  paper: "a4",
  columns: 2,
  margin: (left: 20.5mm, right: 20.5mm, top: 30mm, bottom: 18mm),
  header-ascent: 3mm,
  header: context {
    let pg = counter(page).get().first()
    if pg > %(front)d {
      let on = query(<e>).filter(m => m.location().page() == here().page())
      let before = query(selector(<e>).before(here()))
      let first = if before.len() > 0 { before.last().value } else if on.len() > 0 { on.first().value } else { none }
      let last = if on.len() > 0 { on.last().value } else { first }
      align(center, stack(dir: ttb, spacing: 1.3pt,
        text(weight: "bold", size: 11.5pt, str(pg - %(front)d)),
        line(length: 10mm, stroke: 0.9pt),
        line(length: 10mm, stroke: 0.35pt)))
      v(0.4em)
      grid(columns: (1fr, 1fr), align: (left, right),
        if first != none { guide(first) }, if last != none { guide(last) })
    }
  },
  footer: context {
    let pg = counter(page).get().first()
    if pg > %(front)d and calc.rem(pg - %(front)d - 1, 16) == 0 {
      set text(size: 8pt)
      [Церк.-славян. словарь свящ. Г. Дьяченко.]
      h(1fr)
      [#(calc.quo(pg - %(front)d - 1, 16) + 1)]
    }
  },
  background: context {
    if counter(page).get().first() > %(front)d {
      place(top + left, dx: 105mm, dy: 30mm, line(angle: 90deg, length: 249mm, stroke: 0.35pt))
    }
  },
)
#let e(g, hw, prov, sep, body, ref) = par(hanging-indent: 4.9mm)[
  #metadata(g)<e>#cs(text(size: %(hwsize)spt, fill: if prov { luma(120) } else { black }, hw))#sep#body#ref
]
#let letter(l) = block(width: 100%%, above: 1.6em, below: 0.9em, breakable: false,
  align(center, cs(text(size: 32pt, l + "."))))
#let dis(body) = underline(stroke: 0.35pt + luma(150), offset: 1.6pt, body)
#let ref(s) = text(size: 6.2pt, fill: luma(150))[ ¶#s]

// ---------------------------------------------------------------- title page and note (not in the original)
#page(columns: 1, header: none, footer: none, background: none)[
  #set align(center)
  #v(4fr)
  #block(text(size: 15pt, tracking: 0.15em)[ПОЛНЫЙ])
  #v(0.4em)
  #block(text(size: 22pt, weight: "bold", tracking: 0.08em)[ЦЕРКОВНО-СЛАВЯНСКІЙ СЛОВАРЬ])
  #v(0.6em)
  #block(text(size: 10.5pt)[(со внесеніемъ въ него важнѣйшихъ древне-русскихъ словъ и выраженій)])
  #v(2.2em)
  #block(text(size: 11pt)[Составилъ священникъ магистръ Григорій Дьяченко])
  #v(3fr)
  #block(text(size: 11pt)[МОСКВА · 1900])
  #v(2fr)
  #line(length: 30%%, stroke: 0.4pt)
  #v(1em)
  #block(text(size: 9.5pt)[Digital edition — work in progress \ %(subset_note)s \ generated %(date)s from `djachenko/entries.tsv`])
  #v(3fr)
]
#page(columns: 1, header: none, footer: none, background: none)[
  #set text(size: 9.5pt, lang: "en")
  #set par(hanging-indent: 0pt, justify: true)
  = About this edition
  %(note)s
]
#counter(page).update(%(front)d + 1)
'''

NOTE = r'''
The text was produced from scans of the 1900 edition (Москва, 1900; the author †1903 — public domain). The
segmentation into entries comes from the geometry of the Russian State Library copy (archive.org, 600 ppi); the
wording comes from the text layers of four copies read by two OCR engines, voted character by character
(Cornell University's copy as the primary witness, checked against the 1993 reprint and the Indiana University copy).
On six hand-transcribed test pages the definition text has about one error per hundred characters; most of the
remaining errors sit where the witnesses disagree.

*Headwords.* The Church Slavonic headwords are what no OCR reads reliably. In this build %(n_read)s of %(n_entries)s
headwords have been read from the page images; the remaining %(n_prov)s are printed *grey*: they are the primary
witness's provisional reading and may be garbled or missing. When the reading of the headwords is complete, the
grey will disappear and the alphabetical order will be checked.

*Typography.* The page reproduces the original's setting: its text block, two columns with a rule, the guide
words in Church Slavonic type, the page number over a double rule, the running title with the signature number on
every sixteenth page. Headwords are set in Ponomar Unicode, the rest in Old Standard TT; both fonts are free
(SIL Open Font License). The italics of the original (sources and quotations) are those the OCR detected and are
incomplete. Accents and titla of the Church Slavonic headwords are not reproduced (the letters are).

*Marks.* A small grey ¶ at the end of each entry gives the page and column of the 1900 edition, so that anything
can be verified against the scan.%(marks_note)s Nothing has been proofread yet; a later stage will check the entries
linked to the akathist dictionary (%(n_linked)s lemmas linked so far) and mark them as such.

*Status of the work* (%(date)s): scans and OCR layers acquired; segmentation done; text merged for all %(n_pages)s
pages; headword reading %(pct_read)s complete; structured file `entries.tsv` with %(n_entries)s entries
(%(n_main)s in the main part, %(n_supp)s in the supplement) and %(n_flags)s flagged for checking; errata of the
author not yet applied; proofreading not started.
'''


def fetch_fonts():
    FONTS.mkdir(exist_ok=True)
    for name, url in FONT_FILES.items():
        path = FONTS / name
        if path.exists() and path.stat().st_size > 1000:
            continue
        req = urllib.request.Request(url, headers={'User-Agent': 'akafist-dictionary-build'})
        with urllib.request.urlopen(req, timeout=60) as r:
            path.write_bytes(r.read())
        print('fetched', path.relative_to(ROOT))


def esc(s):
    """Text -> Typst markup-safe text (content context)."""
    s = s.replace('\\', '\\\\')
    for ch in '#$*_`<>@[]~':
        s = s.replace(ch, '\\' + ch)
    s = s.replace('//', '\\/\\/').replace('/*', '/\\*')
    s = re.sub(r'(?<=\S) - (?=\S)', ' — ', s.replace('--', '—'))
    if s[:1] in ('-', '+', '=', '/'):           # would start a list item, a heading or a comment
        s = '\\' + s
    s = re.sub(r'^(\d+)\.(?=\s)', r'\1\\.', s)   # "1. " would start an enumeration
    return s


def spans_of(s):
    return [tuple(int(x) for x in part.split('-')) for part in s.split(';') if part]


def markup(text, italic, disputed, marks):
    """The definition as markup with emph over the italic spans and (optionally) underlines over the disputed."""
    cuts = {0, len(text)}
    for a, b in italic + (disputed if marks else []):
        cuts.update((min(a, len(text)), min(b, len(text))))
    cuts = sorted(cuts)
    out = []
    for a, b in zip(cuts, cuts[1:]):
        seg = esc(text[a:b])
        if any(s <= a and b <= e for s, e in italic):
            seg = f'#emph[{seg}];'
        if marks and any(s <= a and b <= e for s, e in disputed):
            seg = f'#dis[{seg}];'
        out.append(seg)
    return ''.join(out)


def guide_of(hw):
    letters = [c for c in hw if c.isalpha()]
    return ''.join(letters[:3]) + '—' if letters else ''


def load(subset, leaves):
    rows = list(csv.DictReader(open(ENTRIES, encoding='utf-8'), delimiter='\t', quoting=csv.QUOTE_NONE))
    if subset == 'links' and LINKS.exists():
        ids = set()
        for r in csv.DictReader(open(LINKS, encoding='utf-8'), delimiter='\t', quoting=csv.QUOTE_NONE):
            ids.update(x for x in r['ids'].split(';') if x)
        rows = [r for r in rows if r['id'] in ids]
    if leaves:
        rows = [r for r in rows if int(r['id'][:4]) in leaves]
    return rows


def letter_headings(rows):
    """{row index: letter}: where each letter section begins. The manifest names the letters on every leaf; a
    letter that starts on a leaf ("Б,В") is placed before the first entry of that leaf whose headword begins with
    it, else before the first entry of the next leaf. Each letter is placed once per part."""
    letters = {}
    for r in csv.DictReader(open(DJ / 'manifest.tsv', encoding='utf-8'), delimiter='\t'):
        letters[int(r['idx'])] = r['letter'].replace(',', ' ').split()
    out, placed, pending = {}, set(), []
    for i, r in enumerate(rows):
        leaf = int(r['id'][:4])
        Ls = letters.get(leaf, [])
        starts_leaf = i == 0 or int(rows[i - 1]['id'][:4]) != leaf
        if i == 0 or rows[i - 1]['part'] != r['part']:
            placed, pending = set(), []
        for L in Ls:
            if L not in placed and L not in pending:
                pending.append(L)
        if pending:
            first = (r['headword_civil'][:1] or '').lower()
            if first == pending[0].lower() or (starts_leaf and (Ls[:1] == [pending[0]] or pending[0] not in Ls)):
                out[i] = pending.pop(0)
                placed.add(out[i])
    return out


def build(rows, refs, marks, size, leading, hwsize, subset):
    all_rows = list(csv.DictReader(open(ENTRIES, encoding='utf-8'), delimiter='\t', quoting=csv.QUOTE_NONE))
    n_entries = len(all_rows)
    n_prov = sum('hw_provisional' in r['flags'] for r in all_rows)
    n_linked = 0
    if LINKS.exists():
        n_linked = sum(1 for r in csv.DictReader(open(LINKS, encoding='utf-8'), delimiter='\t',
                                                   quoting=csv.QUOTE_NONE) if r['match'] != 'none')
    parts = Counter(r['part'] for r in all_rows)
    n_flags = sum(1 for r in all_rows if set(r['flags'].split(';')) - {'hw_provisional', 'order', 'guessed', ''})
    note = NOTE % dict(n_read=f'{n_entries - n_prov:,}', n_entries=f'{n_entries:,}', n_prov=f'{n_prov:,}',
                       n_linked=n_linked, n_pages=1119, pct_read=f'{(n_entries - n_prov) / n_entries:.0%}',
                       n_main=f'{parts["main"]:,}', n_supp=f'{parts["supplement"]:,}', n_flags=f'{n_flags:,}',
                       date=datetime.date.today().isoformat(),
                       marks_note=(' The places where the witnesses disagree are underlined in grey.' if marks else ''))
    subset_note = {'all': 'main part and supplement, complete',
                   'links': 'the entries linked to the akathist dictionary only'}.get(subset, subset)
    out = [PREAMBLE % dict(size=size, leading=leading, hwsize=hwsize, front=FRONT_PAGES, note=note.strip(),
                           subset_note=subset_note, date=datetime.date.today().isoformat())]
    heading_before = letter_headings(rows)
    part = None
    for i, r in enumerate(rows):
        if r['part'] != part:
            part = r['part']
            if part == 'supplement':
                out.append('#pagebreak()\n#block(width: 100%, above: 0.5em, below: 1.2em, '
                           'align(center, text(size: 14pt, tracking: 0.1em)[ПРИБАВЛЕНІЕ.]))\n')
        if i in heading_before:
            out.append(f'#letter("{heading_before[i]}")\n')
        hw = r['headword'] or '□'
        prov = 'true' if r['hw_source'] == 'D' else 'false'
        sep = {'=': ' = ', '—': ' — ', '(': ' '}.get(r['sep'], ' ')
        body = markup(r['definition'], spans_of(r['italic']), spans_of(r['disputed']), marks)
        ref = f'ref("{r["page"]}{r["col"]}")' if refs else 'none'
        g = guide_of(hw)
        out.append(f'#e("{esc_str(g)}", "{esc_str(hw)}", {prov}, "{sep}", [{body}], {ref})\n')
    TYP.write_text(''.join(out), encoding='utf-8')


def esc_str(s):
    return s.replace('\\', '\\\\').replace('"', '\\"')


def compile_pdf():
    typst = shutil.which('typst')
    if not typst:
        print('typst not found; skipping PDF')
        return
    r = subprocess.run([typst, 'compile', '--font-path', str(FONTS), str(TYP), str(PDF)], capture_output=True,
                       text=True)
    if r.returncode != 0:
        print('typst compile failed:\n', r.stderr[:3000])
        return
    if r.stderr.strip():
        print(r.stderr.strip()[:2000])
    pages = subprocess.run([typst, 'query', '--font-path', str(FONTS), str(TYP), '<e>', '--field', 'value'],
                           capture_output=True, text=True)
    print('wrote', PDF.relative_to(ROOT), f'({PDF.stat().st_size // 1024} KB)')


def parse_ranges(s):
    out = set()
    for part in s.split(','):
        if '-' in part:
            a, b = part.split('-')
            out.update(range(int(a), int(b) + 1))
        else:
            out.add(int(part))
    return out


def main():
    ap = argparse.ArgumentParser(description=__doc__.split('\n\n')[0])
    ap.add_argument('--subset', default='all', choices=('all', 'links'))
    ap.add_argument('--leaves', help='leaves of scan A to include, e.g. 38-60,150')
    ap.add_argument('--no-refs', action='store_true', help='no grey page references')
    ap.add_argument('--marks', action='store_true', help='underline the disputed spans')
    ap.add_argument('--no-pdf', action='store_true')
    ap.add_argument('--size', type=float, default=10.0, help='text size in pt')
    ap.add_argument('--leading', type=float, default=0.56, help='leading in em')
    ap.add_argument('--hwsize', type=float, default=11.2, help='headword size in pt')
    a = ap.parse_args()
    fetch_fonts()
    rows = load(a.subset, parse_ranges(a.leaves) if a.leaves else None)
    build(rows, not a.no_refs, a.marks, a.size, a.leading, a.hwsize, a.subset)
    print(f'{len(rows)} entries -> {TYP.relative_to(ROOT)} ({TYP.stat().st_size // 1024} KB)')
    if not a.no_pdf:
        compile_pdf()


if __name__ == '__main__':
    main()
